### ISSUE TITLE
Planificación tiempo/coste y esfuerzos de cada disciplina

### ISSUE THREAD

**Issue by JulianRoman26** [JulianRoman26/ISOFT2-2021-C01#2]
Tenemos que realizar la planificación del proyecto inicial, que luego seguramente habrá que ir cambiando según el tiempo que le vayamos echando a cada disciplina.

**Comment by zereperez01** [comment]
El archivo que contiene la planificación del proyecto ya ha sido realizado en la reunión del día 22 de octubre
